baseurl = "https://yourusername.github.io/cybersec-portfolio/"
languageCode = "en-us"
theme = "terminal"
pagination.pagerSize = 5

[markup.goldmark.renderer]
  unsafe = true

[params]
  contentTypeName = "posts"
  showMenuItems = 4
  themeColor = "green"
  fullWidthTheme = false
  centerTheme = false

[languages]
  [languages.en]
    title = "CyberSec Portfolio"
    subtitle = "Security Research subtitle = "A simple, retro theme for Hugo" Penetration Testing"
    keywords = ""
    copyright = ""
    menuMore = "Show more"
    readMore = "Read more"
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "CyberSec Portfolio"
      logoHomeLink = "/"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "about"
        name = "About"
        url = "/about"
      [[languages.en.menu.main]]
        identifier = "projects"
        name = "Projects"
        url = "/projects"
      [[languages.en.menu.main]]
        identifier = "blog"
        name = "Blog"
        url = "/posts"
      [[languages.en.menu.main]]
        identifier = "ctf"
        name = "CTF Writeups"
        url = "/ctf"
